### ISSUE TITLE
第三章的3.7公式最后的向量形式

### ISSUE THREAD

**Issue by 363568233** [datawhalechina/pumpkin-book#10]
答案是  XX'/ YY'  应该是向量内积  X'X / Y'Y

**Comment by Sm1les** [comment]
@363568233 感谢您的批评指正，现已修正公式3.7，请您查阅 :)

**Comment by 363568233** [comment]
哈哈  我还写错了 是 X'Y / X'X

**Comment by Sm1les** [comment]
@363568233 哈哈，没事，我理解你的意思 :)
