### ISSUE TITLE
在线的链接无法打开

### ISSUE THREAD

**Issue by pangpang20** [datawhalechina/pumpkin-book#105]
![{1E904F83-116E-4F30-9F7D-F304179BFA26}_20200823231013](https://user-images.githubusercontent.com/8244232/90981852-e3070f80-e595-11ea-864d-ed63c0239393.jpg)

**Comment by Sm1les** [comment]
@pangpang20 由于这个是托管在GitHub，而GitHub服务器在国外，难免存在一些不稳定现象，这个我们也很无奈，建议你下载pdf版本离线查阅
