### ISSUE TITLE
ROC曲线为什么真正例率与假正例率可以同时增加

### ISSUE THREAD

**Issue by zhy102** [datawhalechina/pumpkin-book#106]

**Comment by Sm1les** [comment]
同学你好，你参照南瓜书第2章公式(2.20)里面讲述的ROC曲线画法，自己动手画一下就能知道了

**Comment by zhy102** [comment]
明白了，谢谢啦



---原始邮件---
发件人: ":)s"<notifications@github.com&gt;
发送时间: 2020年9月17日(周四) 下午3:46
收件人: "datawhalechina/pumpkin-book"<pumpkin-book@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"zhy102"<1027884865@qq.com&gt;;
主题: Re: [datawhalechina/pumpkin-book] ROC曲线为什么真正例率与假正例率可以同时增加 (#106)




 
同学你好，你参照南瓜书第2章公式(2.20)里面讲述的ROC曲线画法，自己动手画一下就能知道了
