### ISSUE TITLE
公式(12.39)的解释有问题

### ISSUE THREAD

**Issue by wangkiw** [datawhalechina/pumpkin-book#110]
各位作者好，
1.  南瓜书公式12.39解析中的第三行**因此 σ_i一共有 2^m 种**这个解释应该是想说 **σ有2^m种**情况。
2. 目前我对这个公式还不是很理解(**对σ求期望的操作**)，这个公式的中括号里面应该是先会求到一个h，那么求期望的操作应该是怎么具体作用到中括号里面的这个式子呢？中括号里面的这个式子展开应该是类似于[σ^1h(x_1)+...+σ^mh(x_m)]/m,那么求σ期望的操作应该怎么在这个式子继续往下写呢？

**Comment by archwalker** [comment]
1. 这里意指变量σ有2^m中可能的取值，个人觉得两种说法都是能理解的。
2. 中括号里整个上确界（参见式12.38）对每个σ_i返回一个特定的值，如果把它理解成函数f(σ_i)，再结合外面的求期望就好理解了。

**Comment by wangkiw** [comment]
感谢您的回复，我已经理解了。
