### ISSUE TITLE
书中 公式(3.35)  公式（3.36）怎么没有啊！

### ISSUE THREAD

**Issue by davidqing2000** [datawhalechina/pumpkin-book#114]
书中未发现 公式(3.35)  公式（3.36），它的完整推导式是什么？

**Comment by Sm1les** [comment]
@davidqing2000 同学你好，3.35就是3.32的恒等变形，3.36就是在基于3.35的基础上根据3.36上面的那段话得到的，这个没有啥可推导的，都是一步直接过来的，看书看不明白的话可以看我的视频讲解：https://www.bilibili.com/video/BV1Mh411e7VU?p=5
