### ISSUE TITLE
公式16.16

### ISSUE THREAD

**Issue by summer-la** [datawhalechina/pumpkin-book#115]
对南瓜书里的第三行的Q展开存疑，求和号下面不应该是x‘了吧，应该换个符号吧，以及不懂最后为什么等于V^pi'(x)

**Comment by huskyth** [comment]
后来又解决吗，我也觉得有问题

**Comment by Sm1les** [comment]
@summer-la @huskyth 抱歉，之前16.16的修订版本更新到纸质版里未及时同步到github，现已同步
