### ISSUE TITLE
进不去链接

### ISSUE THREAD

**Issue by moker-monkey** [datawhalechina/pumpkin-book#117]
网址挂了吗？进不去

**Comment by Sm1les** [comment]
哪个网址？我检查了一下readme的所有链接，均能正常打开

**Comment by moker-monkey** [comment]
![image](https://user-images.githubusercontent.com/23519198/129482243-9ffe90fa-39c6-47bd-bc9f-7a23bee6f35e.png)
所有目录里的链接都进不去。。。是不是dns解析的问题？f12了一下，连请求都没发出去，我也测试过我的网络是正常的。

**Comment by Sm1les** [comment]
@moker-monkey 你应该是没搭梯子，建议你下载pdf看

**Comment by moker-monkey** [comment]
了然

**Comment by Huanle** [comment]
> @moker-monkey 你应该是没搭梯子，建议你下载pdf看

请问怎么搭梯子？
