### ISSUE TITLE
式 2.27

### ISSUE THREAD

**Issue by iwanttobepowerful** [datawhalechina/pumpkin-book#118]
![image](https://user-images.githubusercontent.com/30350667/132316711-b8b9d720-ad37-4464-bde7-da3b11450d07.png)
![image](https://user-images.githubusercontent.com/30350667/132316583-186e595e-dac8-43a6-b8bd-331bbc1a4f26.png)

**Comment by Sm1les** [comment]
同学你好，这个地方我认为是周老师笔误，错把i写成1了，你可以看下我的推导

**Comment by iwanttobepowerful** [comment]
> 同学你好，这个地方我认为是周老师笔误，错把i写成1了，你可以看下我的推导

请您告知周老师吧，我可能表述不清楚，多谢~
