### ISSUE TITLE
第五章 式(5.2) 中最后推导梯度的时候，\hat(yi)也应该是关于w的函数，没有对其求导，直接当成常数处理了，这似乎是不正确的。

### ISSUE THREAD

**Issue by wanyixue** [datawhalechina/pumpkin-book#128]
\hat(yi)应该是阶越函数的输出，而阶越函数不可导，也没有subgradient，30页直接将\hat(yi)写入了求导的结果，似乎是不正确的。

**Comment by Sm1les** [comment]
已在https://github.com/datawhalechina/pumpkin-book/issues/64#issuecomment-1474869078 答复
