### ISSUE TITLE
There are no page numbers in the most recent PDF file pages

### ISSUE THREAD

**Issue by Rycen7822** [datawhalechina/pumpkin-book#130]
There are no page numbers in the most recent PDF file pages

**Comment by mrxiaojie** [comment]
晚上好！您的邮件我已经收到了，谢谢您的支持！

**Comment by Rycen7822** [comment]
actually, it's version 2.0.0, only video links are in the header and footer

**Comment by Sm1les** [comment]
in order to place the video link, we have to sacrifice the page number.
