### ISSUE TITLE
v2.0.0版本的PDF中10.5.1节有关主成分分析的推导流程有处错误

### ISSUE THREAD

**Issue by huishengye** [datawhalechina/pumpkin-book#131]
release版本：https://github.com/datawhalechina/pumpkin-book/releases/tag/v2.0.0
节次： 10.5.1 《式（10.14）的推导》
位置：推导过程⑥，其中$-x_{i}^{T}W^{T}x_{i}$ 应该为$-x_{i}^{T}WW^{T}x_{i}$  。

如若反馈有误请指正，感谢作者们的贡献。

**Comment by mrxiaojie** [comment]
下午好！您的邮件我已经收到了，谢谢您的支持！

**Comment by bghfcd19900** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Sm1les** [comment]
同学你好，你反馈的没错，是我们笔误了，感谢指正💐
