### ISSUE TITLE
西瓜书问题

### ISSUE THREAD

**Issue by silence-watcher** [datawhalechina/pumpkin-book#134]
2016.1月1版第54页公式3.7的分子上x与y似乎反了。
![微信图片_20240713155008](https://github.com/user-attachments/assets/e0b75a70-d94b-4e28-a474-b111fc1398f4)

**Comment by Sm1les** [comment]
西瓜书的勘误表在这里：https://cs.nju.edu.cn/zhouzh/zhouzh.files/publication/MLbook2016.htm ，可以对应查阅一下
