### ISSUE TITLE
Logo Design Offering as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [datawhalechina/pumpkin-book#21]
Hello Sir. I'm a Graphics Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks for the attention.

**Comment by Sm1les** [comment]
Thanks for your kindness. But we have had some of our internal members doing this. I am sorry for this, looking forward to the next cooperation :)
