### ISSUE TITLE
公式1.2中的第二步到第三步还是没有看明白？

### ISSUE THREAD

**Issue by duniang818** [datawhalechina/pumpkin-book#39]
# 西瓜书待推导或待解析公式征集

若南瓜书里没有你想要查阅的公式，请[点击这里](https://github.com/datawhalechina/pumpkin-book/issues/1)提交你希望补充推导或者解析的公式编号，我们看到后会尽快进行补充。

## 如果有其他疑问：

欢迎加微信公众号：Datawhale，添加公众号后联系我们。
![Datawhale，一个专注于AI领域的学习圈子。初衷是for the learner，和学习者一起成长。目前加入学习社群的人数已经数千人，组织了机器学习，深度学习，数据分析，数据挖掘，爬虫，编程，统计学，Mysql，数据竞赛等多个领域的内容学习，微信搜索公众号Datawhale可以加入我们。](https://raw.githubusercontent.com/datawhalechina/pumpkin-book/master/res/qrcode.jpeg "Datawhale，一个专注于AI领域的学习圈子。初衷是for the learner，和学习者一起成长。目前加入学习社群的人数已经数千人，组织了机器学习，深度学习，数据分析，数据挖掘，爬虫，编程，统计学，Mysql，数据竞赛等多个领域的内容学习，微信搜索公众号Datawhale可以加入我们。")

**Comment by xiaoxiaoyao** [comment]
亲，具体是哪里不明白呢？

**Comment by Sm1les** [comment]
@duniang818 同学你好，我对第二步到第三步又补充了点内容，你看看还能看懂吗？
