### ISSUE TITLE
第七章7.5.1节中的 7.27 公式

### ISSUE THREAD

**Issue by xinquan2008** [datawhalechina/pumpkin-book#44]
请在这里写上你具体哪一个章节哪一个公式不理解，如果能写清哪里不理解那就最好啦~

7.27 ，第二个步骤，为什么直接得出 P(X)P(Y)，而不是 P(X,Y)

**Comment by Sm1les** [comment]
@xinquan2008 同学你好，这个需要你结合这个V型结构的本身的含义去理解，因为在不考虑x4的情况下，x1和x2本身就是两个独立的随机变量，所以产生x1和x2的概率就是简单的P(x1)P(x2)。
