### ISSUE TITLE
公式7.23和西瓜书不一样

### ISSUE THREAD

**Issue by OriginPrince** [datawhalechina/pumpkin-book#47]
您好，南瓜书公式7.23和西瓜书不一样，证明公式也缺少j，好像有点问题。谢谢

**Comment by Sm1les** [comment]
同学你还，感谢你的纠错，现已更正，麻烦你再查阅一下，看还有问题吗？ :)

**Comment by Sm1les** [comment]
同学你好，感谢你的纠错，现已更正，麻烦你再查阅一下，看还有问题吗？ :)

**Comment by OriginPrince** [comment]
没有问题了  谢谢你们
