### ISSUE TITLE
第六章（6.21）怎么推导呢？

### ISSUE THREAD

**Issue by flitdu** [datawhalechina/pumpkin-book#49]
为何（6.21）里面没有b 呢？？？

**Comment by Sm1les** [comment]
同学你好，这是因为和前面6.11一样，只要求出了alpha的值，自然也就求出了w和b。

**Comment by flitdu** [comment]
嗯嗯，李航的书上更详细点
thank you

**Comment by Sm1les** [comment]
@flitdu 嗯嗯，是的，西瓜书搭配小蓝书也是极好的。
