### ISSUE TITLE
prml公式推导有考虑做吗

### ISSUE THREAD

**Issue by ChengYeung1222** [datawhalechina/pumpkin-book#56]
希望这本经典也能拥有一本“南瓜书”

**Comment by Sm1les** [comment]
同学你好，目前精力有限，南瓜书尚且还有很多欠缺，我们即使有这心也力不足，所以目前暂未考虑给PRML做一本“南瓜书”，但是后期如果有足够精力我们会考虑的。

**Comment by ZhangYikaii** [comment]
加油!
