### ISSUE TITLE
第二章2.21

### ISSUE THREAD

**Issue by zhanghexie** [datawhalechina/pumpkin-book#57]
第二章2.21中不应该有蓝线m3吧，按照书上的的定义，按顺序**逐个**把样本作为正例并计算出两个重要值……
如果出现斜线意思也不应该写的那个意思吧，而应该是有一个即是正例又是反例的例子被判断为正例。显然没有这种情况。
我认为Lrank公式中正反例预测值相等时罚0.5分是因为认为预测值相同时，反例会排在正例前面的概率为0.5。

**Comment by Sm1les** [comment]
同学你好，书上说的是“将分类阈值依次设为每个样例的预测值”，并不是“按顺序逐个把样本作为正例”。

**Comment by zhanghexie** [comment]
不是的，书上说的是“我们根据机器学习的预测结果对样本进行排序，按此顺序逐个把样本作为正例预测，每次计算……”（西瓜书33页倒数第一段）

**Comment by Sm1les** [comment]
@zhanghexie 同学你好，33页那句话是不能严格扣字面意思的，那里我觉得是周老师进行一个简单的概述而已，不能作为画ROC曲线的标准规范，那句话要理解也应该理解为“按顺序逐个把样本的预测值作为分类阈值来判别正例”，也就是和34页的倒数第三段的倒数第四句话“将分类阈值依次设为每个样例的预测值”是同一个意思，因为画ROC曲线的标准规范就是34页的倒数第三段给出的，同时我们对公式2.21的解析也是严格基于这一段话的。

**Comment by zhanghexie** [comment]
> @Sm1les  好的，知道了，多谢大佬指点。
