### ISSUE TITLE
13章13.4公式

### ISSUE THREAD

**Issue by gwloveyou** [datawhalechina/pumpkin-book#58]
感觉13.4公式里面的第一项里的 . 乘号前面的内容应该是公式13.3的内容吧，但是为什么把13.3的分子ai.p(x|ui,Mi) 给去掉了并且只剩下分母的倒数了。

**Comment by LeoLRH** [comment]
您好，谢谢你的提问首先我不太明白你想问什么是问题，你是说我的公式推错了呢（公式意义不明白还是我写错了），我理解这个公式就是，首先13.3是第九章9.4.3 节的式(9.30)，具体推导参见有关式(9.30)的解释（如果还不明白可以再来这一章节找我）。13.4公式他的意思就是我个人理解：就是对
该式针对有标记样本（第一项）和无标记样本（第二项）计算相似似然，因为有标记样本的类别是确定的，因此在计算它的对数似然时，它只可能来自N个高斯混合成分中的一个（西瓜书第 296 页第 2 行提到“假设样本由高斯混合模型生成，且每个类别对应一个高斯混合成分”），所以计算第 1 项计算有标记样本似然时乘以那一项
