### ISSUE TITLE
考虑将推导过程中sgn函数统一为sign函数

### ISSUE THREAD

**Issue by onshek** [datawhalechina/pumpkin-book#85]
如题，希望与西瓜书符号体系保持一致，是否考虑将各章推导过程中的$sgn$统一为$sign$？

**Comment by Sm1les** [comment]
同学你好，我们的撰写规范是默认以西瓜书的符号体系保持一致的，但是可能存在一些人为的纰漏，我们这就全盘扫描修订一下，感谢你的反馈 :)
