### ISSUE TITLE
图8.11 第三行Map符号是什么意思

### ISSUE THREAD

**Issue by shuifan1** [datawhalechina/pumpkin-book#86]

**Comment by Sm1les** [comment]
同学你好，图8.11左侧小字有解释 :)

**Comment by shuifan1** [comment]
收到，谢谢。   Map 就是一个映射的意思吧。看解释的不是很清楚


















在 2020-04-16 16:06:40，":)s" <notifications@github.com> 写道：

同学你好，图8.11左侧小字有解释 :)
