### ISSUE TITLE
第二章疑似笔误

### ISSUE THREAD

**Issue by Ricardofd** [datawhalechina/pumpkin-book#89]
南瓜书pdf第2页
接下来我们需要把分类阈值**从小到大**依次设为每个样本的预测值，也就是依次 设为 0.77￿0.62￿0.58￿0.47￿0.33￿0.23￿0.15，然后每次计算真正例率和假正例率，再在相应的坐标上打一个点， 最后再将各个点用直线串连起来即可得到 ROC 曲线。

应该是从大到小吧？

**Comment by Sm1les** [comment]
@Ricardofd 同学你好，是笔误，感谢你的反馈 :)
