### ISSUE TITLE
建议尝试一下 GNU TeXmacs

### ISSUE THREAD

**Issue by sadhen** [datawhalechina/pumpkin-book#9]

**Comment by spareribs** [comment]
http://www.texmacs.org/tmweb/home/welcome.en.html  这个吗？看起来很厉害的样子

**Comment by Sm1les** [comment]
好的，感谢您的建议，目前markdown+docsify能基本满足我们的需求，如果后期有其他需求而markdown+docsify无法满足的话我们会考虑更换 :)
