### ISSUE TITLE
十二章疑似笔误

### ISSUE THREAD

**Issue by Ricardofd** [datawhalechina/pumpkin-book#93]
公式(12.36)
**y_i=1, h(x_i)=1, 则Ⅱ（y_i≠h(x_i)）=1**
这里Ⅱ（y_i≠h(x_i)）是不是应该等于0啊...
我这个菜鸡不会在github里用latex公式，见笑了=_=
​

**Comment by archwalker** [comment]
您好，这里是笔误，已修正，感谢反馈！
