### ISSUE TITLE
Single quotation marks should be used instead.

### ISSUE THREAD

**Issue by septsea** [datawhalechina/pumpkin-book#99]
In [the README file](https://github.com/datawhalechina/pumpkin-book/blob/master/README.md), `“不太友好”` should be replaced by `‘不太友好’`, because when quotation marks are in quotation marks, they should be altered. In Simplified Chinese, we start with double quotation marks, so the next set of quotation marks is single. Here is an example:
```
"zzz 'zzzz zz' zz 'zzzz "zz" z'"
```

**Comment by Sm1les** [comment]
问题不大
